image: node:16

stages:
  - Code quality
  - Testing
  - Deployment

prettier/eslint/build:
  stage: Code quality
  retry: 1
  script:
    - cd frontend
    - npm ci --silent
    - cd ../backend
    - npm ci --silent
    - npm run prettier
    - npm run lint
    - cd ../frontend
    - npm run prettier
    - npm run lint
    - npm run build

jest/cypress:
  image: cypress/base:16
  stage: Testing
  retry: 1
  services:
    - mongo
  variables:
    MONGO_URI: "mongodb://mongo/rickandmorty"
    NODE_ENV: "test"
  script:
    - cd frontend
    - npm ci --silent
    - cd ../backend
    - npm run setup:production
    - npm run start &
    - cd ../frontend
    - echo "Unit tests"
    - npm run test
    - echo "End to end tests"
    - npm run test:e2e:ci

deploy:
  stage: Deployment
  retry: 1
  before_script:
    ## Set up SSH keys and stuff
    ## See https://filip5114.github.io/GitLab-CI-Pipeline-SSH/
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    ## Check if SSH works so it can fail before installing and building
    - ssh $SSH_USER@$VM_IPADDRESS -oStrictHostKeyChecking=no "echo 'Testing SSH Connection...'"
    ## Copy backend code to VM
    - scp -r ./backend/* $SSH_USER@$VM_IPADDRESS:/lhome/mikkesva/backend
    - scp -r ./types/* $SSH_USER@$VM_IPADDRESS:/lhome/mikkesva/types
    ## Re-setup database and restart Node application
    - ssh $SSH_USER@$VM_IPADDRESS -oStrictHostKeyChecking=no "cd /lhome/mikkesva/backend && npm ci && pm2 stop all; npm run setup:production && pm2 start src/index.ts || pm2 restart all"
    ## Build React app
    - cd frontend
    - npm ci --silent
    - npm run build
    ## SSH into VM to remove previous React build
    - ssh $SSH_USER@$VM_IPADDRESS -oStrictHostKeyChecking=no "rm -rf /var/www/html/project3/*"
    ## Copy React build files to VM
    - scp -r ./build/* $SSH_USER@$VM_IPADDRESS:/var/www/html/project3
  only:
    - main
