image: node:16

stages:
  - Formatting
  - Linting
  - Testing
  - Building
  - Deployment

prettier:
  stage: Formatting
  retry: 1
  script:
    - cd frontend
    - npm ci
    - npm run prettier
    - cd ../backend
    - npm ci
    - npm run prettier

eslint:
  stage: Linting
  retry: 1
  script:
    - cd frontend
    - npm ci
    - npm run lint
    - cd ../backend
    - npm ci
    - npm run lint

tests:
  image: cypress/base:16
  stage: Testing
  retry: 1
  script:
    - cd frontend
    - npm ci
    - npm run start &
    - npx cypress run -q
    - npm run test

react-build:
  stage: Building
  retry: 1
  script:
    - cd frontend
    - npm ci
    - npm run build

deploy:
  stage: Deployment
  retry: 1
  before_script:
    ## Set up SSH keys and stuff
    ## See https://filip5114.github.io/GitLab-CI-Pipeline-SSH/
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    ## Check if SSH works so it can fail before installing and building
    - ssh $SSH_USER@$VM_IPADDRESS -oStrictHostKeyChecking=no "echo 'Testing SSH Connection...'"
    ## Copy backend code to VM
    - scp -r ./backend/* $SSH_USER@$VM_IPADDRESS:/lhome/mikkesva/backend
    ## Reset and set up the database
    ## Re-setup database and restart Node application
    - ssh $SSH_USER@$VM_IPADDRESS -oStrictHostKeyChecking=no "cd /lhome/mikkesva/backend && npm ci && pm2 stop all; npm run setup:production && pm2 start src/index.js || pm2 restart all"
    ## Build React app
    - cd frontend
    - npm ci
    - npm run build
    ## SSH into VM to remove previous React build
    - ssh $SSH_USER@$VM_IPADDRESS -oStrictHostKeyChecking=no "rm -rf /var/www/html/project3/*"
    ## Copy React build files to VM
    - scp -r ./build/* $SSH_USER@$VM_IPADDRESS:/var/www/html/project3
  only:
    - main
